use HumanResourceDB
SELECT [PERSONAL_ID] as [ID], [BIRTH_DATE] AS [Birthdate]
FROM [PERSONAL]

-- even me not get it, please dont ask, just run the query
SELECT [PERSONAL_ID] AS [ID], 
	[CURRENT_LAST_NAME] + ' ' + [CURRENT_MIDDLE_NAME] + ' ' + [CURRENT_FIRST_NAME] AS [Fullname], 
	[BIRTH_DATE] AS [Birthdate], 
	DATEDIFF(DAY, GETDATE(), DATEFROMPARTS(YEAR(GETDATE()) 
		+ CASE WHEN MONTH([BIRTH_DATE]) > MONTH(GETDATE()) 
			OR (MONTH([BIRTH_DATE]) = MONTH(GETDATE()) 
			AND DAY([BIRTH_DATE]) > DAY(GETDATE())) 
		THEN 0 ELSE 1 END, 
		MONTH([BIRTH_DATE]), DAY([BIRTH_DATE]))) AS [Upcomming] 
	FROM [DBO].[PERSONAL] 
	WHERE DATEFROMPARTS(YEAR(GETDATE()) 
	+ CASE WHEN MONTH([BIRTH_DATE]) > MONTH(GETDATE()) 
	OR (MONTH([BIRTH_DATE]) = MONTH(GETDATE()) 
	AND DAY([BIRTH_DATE]) > DAY(GETDATE())) 
	THEN 0 ELSE 1 END, 
	MONTH([BIRTH_DATE]), 
	DAY([BIRTH_DATE])) 
	BETWEEN GETDATE() 
	AND DATEADD(DAY, 365, GETDATE()) 
	ORDER BY [Upcomming];

SELECT [P].[PERSONAL_ID] AS [ID], 
	([P].[CURRENT_LAST_NAME] + ' ' + [P].[CURRENT_MIDDLE_NAME] + ' ' + [P].[CURRENT_FIRST_NAME]) AS [FULLNAME], 
	[E].[HIRE_DATE_FOR_WORKING] AS [HIRE DATE], 
	DATEDIFF(DAY, GETDATE(), DATEFROMPARTS(YEAR(GETDATE()) 
		+ CASE WHEN MONTH([E].[HIRE_DATE_FOR_WORKING]) > MONTH(GETDATE()) 
			OR (MONTH([E].[HIRE_DATE_FOR_WORKING]) = MONTH(GETDATE()) 
			AND DAY([E].[HIRE_DATE_FOR_WORKING]) > DAY(GETDATE())) 
		THEN 0 ELSE 1 END, 
		MONTH([E].[HIRE_DATE_FOR_WORKING]), 
		DAY([E].[HIRE_DATE_FOR_WORKING]))) AS [UPCOMING] 
	FROM [DBO].[PERSONAL] [P], [DBO].[EMPLOYMENT] [E] 
	WHERE DATEFROMPARTS(YEAR(GETDATE()) 
		+ CASE WHEN MONTH([E].[HIRE_DATE_FOR_WORKING]) > MONTH(GETDATE()) 
			OR (MONTH([E].[HIRE_DATE_FOR_WORKING]) = MONTH(GETDATE()) 
			AND DAY([E].[HIRE_DATE_FOR_WORKING]) > DAY(GETDATE())) 
		THEN 0 ELSE 1 END, 
		MONTH([E].[HIRE_DATE_FOR_WORKING]), 
		DAY([E].[HIRE_DATE_FOR_WORKING])) 
		BETWEEN GETDATE() 
		AND DATEADD(DAY, 365, GETDATE()) 
		AND [P].[PERSONAL_ID] = [E].[PERSONAL_ID]
	GROUP BY [P].[PERSONAL_ID], [P].[CURRENT_LAST_NAME], [P].[CURRENT_MIDDLE_NAME], [P].[CURRENT_FIRST_NAME], [E].[HIRE_DATE_FOR_WORKING]
	ORDER BY [UPCOMING];

SELECT [P].[PERSONAL_ID] AS [ID], 
	[P].[CURRENT_LAST_NAME] + ' ' + [P].[CURRENT_MIDDLE_NAME] + ' ' + [P].[CURRENT_FIRST_NAME] AS [Fullname],
	CONVERT(VARCHAR, ewt.MONTH_WORKING) + '/' + CONVERT(VARCHAR, year(ewt.YEAR_WORKING)) as [Duration],
    [EWT].[TOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH] as [Vacation days]
FROM [DBO].[EMPLOYMENT_WORKING_TIME] [EWT],
	[DBO].[PERSONAL] [P],
	[DBO].[EMPLOYMENT] [E]